#!/bin/bash

#USAGE : form inputfile outputfile
#INPUT FILE TEMPLATE : the file "i" is sample input , but basic template :

#   TITLE:Title of the Form Page
#   DESC:Description about form
#   FIELDS:[ field1 | field 1 description ], [ field2 | field2 description ], [ field3 description ]
#

form() {

	desc="$(cat $1 | readr DESC)"
	title="$(cat $1 | readr TITLE)"
	fields="$(cat $1 | readr FIELDS)"


	#store fields seperately on different lines
	fields=$(echo "$fields" | rep "," "
	")


	#this isn't even my
	finalform=""


	#INPUT TEMPLATE :

	inputtemplate="
	<div class=\"fieldelement\">
	<h3 class=\"fieldname\">FIELD</h3>

	<p class=\"fielddesc\" >DESCRIPTOR</p>

	INPUTFORM

	</div>

	"

	outputtemplate="

	<html>

		<head>
			<title>TITLE</title>
		</head>
		
		<body>
			
			<h1>TITLE</h1>
			
			<p>DESC</p>
			
			<form>
				FORM
		                <br>
		                <input id="submitbutton" type=\"submit\" value=\"Submit\">

			</form>
			
		</body>

	</html>
	"



	#process all fields, one by one

	echo "$fields" > .tmp

	while read line; 
	do 

		#storing id, removing spaces.
		id=$( echo $line | del "[" | del "|*]" | rep " " "_" )
		
		#html form creation with id
		inputform=$( echo "<input class=\"field\" type="text" name=\"$id\">")

		
		#getting input descriptor
		inputfielddescriptor=$( echo $line | del "*|" | del "]")

		
		#getting field
		inputfieldname=$( echo $line | del "[" | del "|*]" )
		
		tempform=$( echo $inputtemplate | rep FIELD "$inputfieldname" | rep DESCRIPTOR "$inputfielddescriptor" | rep INPUTFORM "$inputform" )
		
		outputtemplate=$( echo $outputtemplate | rep FORM "$tempform

			FORM")
		
		
	done < .tmp

	echo "$outputtemplate" |
	del FORM |
	rep DESC "$desc" |
	rep TITLE "$title" > $2

	rm .tmp

}

form "$@"
